name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    if: ${{ contains(github.event.head_commit.message, '#build') }}

    strategy:
      matrix:
        #os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # Specify electron-builder config file
          args: -c electron-builder.json5

          # NPM script to execute before electron-builder
          build_script_name: prebuild

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # Used for mac signing
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          APPLE_ID: ${{ secrets.api_key_id }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.app_specific_password }}
      
      - name: Upload Mac artifact
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: heynote-macos-${{ github.sha }}
          path: release/*/Heynote_[0-9].[0-9].[0-9]*.zip
          retention-days: 1
      
      - name: Upload Windows artifact
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: heynote-windows-${{ github.sha }}
          path: release/*/Heynote_[0-9].[0-9].[0-9]*.exe
          retention-days: 1
